name: Api Tests
env:
    GH_TOKEN: ${{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}}
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: Npm Install
        run: npm ci
      - name: __tests__
        run: gh repo clone JetiMax/FrTest
