name: Api Test
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v1.2.1
        with:
          node-version: 16.13.x
          cache: npm      
          
      - name: Run Tests
        run: npm run test
      

        
